KHAYAAL-2-leader description component created
roshan1999/interns-khayaal-app pull request #8
Opened 2022-05-25 05:55 UTC by preethisun0801

leader description component created

2022-05-25 07:21 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.jsx
> +const LeaderDescription = ({name,position,desc}) => {
take input as props and use further.

2022-05-25 07:22 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.jsx
> +            <h2 className="leaderName">{name}</h2>
Use props.nameText, props.positionText, props.descriptionText

2022-05-25 07:23 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    font-size: 38px;
font size should change with screen size. Refer home page to see how font changes with screen size

2022-05-25 07:23 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    font-size:21px;
font size should change with screen size. Refer home page to see how font changes with screen size

2022-05-25 07:23 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    font-size: 15px;
font size should change with screen size. Refer home page to see how font changes with screen size

2022-05-25 07:24 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    color: #2e244b;
No hardcoding of color. Refer styles/colors.css for the color. Take the closest color to it from the design. 
Refer homepage on how to include the color from colors.css to here

2022-05-25 07:24 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    color:#885F88;
No hardcoding of color. Refer styles/colors.css for the color. Take the closest color to it from the design.
Refer homepage on how to include the color from colors.css to here

2022-05-25 07:24 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    color:#686868;
No hardcoding of color. Refer styles/colors.css for the color. Take the closest color to it from the design.
Refer homepage on how to include the color from colors.css to here

2022-05-25 07:25 UTC, roshan1999 commented on src/Components/OurTeams/LeaderDescription.css
> +    line-height: 38px;
px -> make note, to make it look good when different screen sizes are used

2022-05-25 07:26 UTC, roshan1999 requested changes
Make note of all screen sizes and px will work only for one screen size and will be too small for other screen sizes

2022-05-25 08:42 UTC, preethisun0801 commented
props changed, fonts changed from px to rem, colors changed from hardcoded to var from colors.css

2022-05-25 13:20 UTC, preethisun0801 commented
[KHAYAAL-2.docx](https://github.com/roshan1999/interns-khayaal-app/files/8771472/KHAYAAL-2.docx)

2022-05-26 02:24 UTC, roshan1999 approved these changes

2022-05-26 02:27 UTC, merged