Khayaal 7 divider and heading
roshan1999/interns-khayaal-app pull request #9
Opened 2022-05-25 06:09 UTC by preethisun0801

our teams divider and heading

2022-05-25 07:31 UTC, roshan1999 commented on src/Components/OurTeams/DividerAndHeading.css
> +  left: 0%;
dont use absolute, use flexbox

2022-05-25 07:32 UTC, roshan1999 requested changes
Address all changes from leader description component over here as well

2022-05-25 08:56 UTC, preethisun0801 commented
flexbox used for divider, font size and color changed for generalisation

2022-05-25 13:20 UTC, preethisun0801 commented
[KHAYAAL-7.docx](https://github.com/roshan1999/interns-khayaal-app/files/8771475/KHAYAAL-7.docx)

2022-05-26 02:32 UTC, roshan1999 approved these changes

2022-05-26 02:34 UTC, merged